# Generated by Django 5.2.7 on 2025-11-17 01:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('reward_rate', models.DecimalField(decimal_places=3, help_text='Points awarded per 1.00 currency unit', max_digits=6)),
                ('redemption_points', models.PositiveIntegerField(help_text='Amount of points needed to redeem a reward')),
                ('redemption_rate', models.DecimalField(decimal_places=2, help_text='Discount percentage in decimal form for reward on a redemption', max_digits=3)),
                ('logo_url', models.URLField()),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.customer')),
            ],
            options={
                'unique_together': {('business', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apple_pass_id', models.CharField(blank=True, max_length=128, null=True)),
                ('google_pass_id', models.CharField(blank=True, max_length=128, null=True)),
                ('apple_push_token', models.CharField(blank=True, max_length=256, null=True)),
                ('wallet_status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('apple_auth_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('business_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businesscustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('public_slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('prepared_loyalty_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_stations', to='api.loyaltycard')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('points_redeemed', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loyaltycard')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
            ],
        ),
        migrations.CreateModel(
            name='PassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_library_identifier', models.CharField(max_length=64)),
                ('pass_type_identifier', models.CharField(max_length=128)),
                ('push_token', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loyalty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_registrations', to='api.loyaltycard')),
            ],
            options={
                'unique_together': {('loyalty_card', 'device_library_identifier', 'pass_type_identifier')},
            },
        ),
    ]
