# Generated by Django 5.2.7 on 2025-11-13 05:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='prepared_loyalty_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_stations', to='api.loyaltycard'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='points_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
