# Generated by Django 5.2.7 on 2025-11-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_station_prepared_at_station_prepared_loyalty_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='apple_auth_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_library_identifier', models.CharField(max_length=64)),
                ('pass_type_identifier', models.CharField(max_length=128)),
                ('push_token', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loyalty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_registrations', to='api.loyaltycard')),
            ],
            options={
                'unique_together': {('loyalty_card', 'device_library_identifier', 'pass_type_identifier')},
            },
        ),
    ]
