# Generated by Django 5.2.7 on 2025-11-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loyaltycard_apple_auth_token_passregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='loyalty_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loyaltycard'),
        ),
    ]
